name: Ignition
on:
  push:
    branches: [ main ]
jobs:
  ignition:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Generate ignition file
        run: docker run --interactive --rm quay.io/coreos/butane:release --pretty --strict < ${GITHUB_WORKSPACE}/config.bu
